lNames = [
'Alan_Turing',
'Albert_Einstein',
'Albert_Sabin',
'Alexander_Fleming',
'Alexander_Graham_Bell',
'Alexander_von_Humboldt',
'Antoine_de_Saint-Exupéry',
'Carl_Friedrich_Gauß',
'Charles_Darwin',
'Christoph_Kolumbus',
'Dmitri_Mendelejew',
'Edwin_Hubble',
'Ferdinand_Magellan',
'Fritz_Haber',
'Galileo_Galilei',
'Gottfried_Wilhelm_Leibniz',
'Gregor_Mendel',
'Henry_Ford',
'Isaac_Newton',
'James_Watson',
'Johannes_Kepler',
'Jonas_Salk',
'Konrad_Zuse',
'Leonardo_da_Vinci',
'Linus_Pauling',
'Louis_Pasteur',
'Marco_Polo',
'Marie_Curie',
'Max_Planck',
'Michelangelo',
'Neil_Armstrong',
'Nicolaus_Copernicus',
'Niels_Bohr',
'Nikola_Tesla',
'Otto_Hahn',
'Pablo_Picasso',
'Robert_Oppenheimer',
'Srinivasa_Ramanujan',
'Stephen_Hawking',
'Thomas_Edison',
'Vasco_da_Gama',
'Vereinigte_Staaten',
'Vincent_van_Gogh',
'Werner_Heisenberg',
'Wernher_von_Braun',
'Wilhelm_Röntgen',
]

lNames_new = []
for name in lNames:
  if not '_' in name:
    print(name)
